lichess-org/scalachess

src/main/scala/Actor.scala
src/main/scala/Move.scala
src/main/scala/Replay.scala
src/main/scala/variant/Atomic.scala
src/main/scala/variant/Threecheck.scala
src/main/scala/variant/Variant.scala
src/test/scala/AtomicVariantTest.scala

Applying variant effects to moves as they are calculated so that we can factor the effect (for example, a piece next to a piece blocking check in Atomic chess) into deciding whether a king is endangered by a move or not.
Submitting as a pull request in case there are any situations I haven't considered where a move is constructed and needs to be finalised. I think (although I'm not sure) Replay.scala covers takebacks.

Finalise move on creation

---

src/main/scala/variant/Horde.scala
src/main/scala/variant/Variant.scala

This is no longer a security issue or bug for lichess, since you can not setup positions for Horde chess. Anyway, two improvements related to Horde chess:
* It's not a problem to allow pawns on the backrank. Only the promotion rank of the relative side is an issue.
* We should also validate incorrect Horde chess starting positions.

adjust pawns on promotion rank validation for Horde chess

---

src/main/scala/format/Forsyth.scala
src/test/scala/format/ForsythTest.scala

We need to verify that:
* the en-passant square is on rank 3, if black is to move
* the en-passant square is on rank 6, if white is to move
* there is a pawn of the opposite color on the fifth rank and the correct en-passant file (from our pov)
* the square on the seventh and sixth rank was left behind empty
Please review carefully. Also, it is very likely that there is more elegant Scala for this. I'd like to learn ;)

validate enpassant squares

---

src/main/scala/Actor.scala
src/main/scala/Board.scala
src/main/scala/InsufficientMatingMaterial.scala
src/main/scala/Situation.scala
src/main/scala/variant/Antichess.scala
src/main/scala/variant/Atomic.scala
src/main/scala/variant/Horde.scala
src/main/scala/variant/KingOfTheHill.scala
src/main/scala/variant/Threecheck.scala
src/main/scala/variant/Variant.scala
src/test/scala/AntichessVariantTest.scala
src/test/scala/AtomicVariantTest.scala
src/test/scala/HordeVariantTest.scala
src/test/scala/VariantTest.scala

This pull request fixes some of the issues highlighted in: https://github.com/ornicar/lila/issues/773
If a stronger player flags against a player who doesn't have sufficient material to win, the game will be a draw.
**Requires a change to lila**. If accepted, the following line https://github.com/ornicar/lila/blob/b73800ddb46eff91a64963fc9b895cbb893b4fb4/modules/round/src/main/Round.scala#L215 will have to be updated to use the variant's 'insufficientWinningMaterial' method.
It's possible that the autodraw condition for atomic that we've had for a while might not be appropriate. Perhaps we can raise a separate issue to consider the debate in http://en.lichess.org/forum/team-atomic-chess-theoreticians/help-fix-a-lichess-bug-insufficient-material-in-atomic or update to this end rather than …

Apply insufficient winning material when flagging to atomic and horde variants

---

src/main/scala/Hash.scala
src/main/scala/Move.scala
src/test/scala/HashTest.scala

this is a failing test with the bug.
capturing the king does not remove castling rights. parsing a fen with a missing king will remove castling rights.
(aditionally, since castling is disallowed in racing kings and antichess, it's probably best to get rid of castling rights entirely in those cases.)

hash consistency when king is captured

---

src/main/scala/Board.scala
src/main/scala/Setup.scala
src/main/scala/format/Forsyth.scala
src/main/scala/variant/Antichess.scala
src/main/scala/variant/Horde.scala
src/main/scala/variant/RacingKings.scala
src/main/scala/variant/Variant.scala
src/test/scala/AntichessVariantTest.scala
src/test/scala/BoardTest.scala
src/test/scala/VariantTest.scala
src/test/scala/format/ForsythTest.scala

As far as the opening explorer and hash consistency are concerned, #66 did the job. However boards should also be initialized with the correct castling rights (in the first place).

castling right initialization for variants

---

src/main/scala/Board.scala
src/main/scala/Move.scala
src/main/scala/Situation.scala
src/main/scala/format/Forsyth.scala
src/test/scala/HashTest.scala
src/test/scala/format/ForsythTest.scala

castling rights should be removed, then. here's a failing test.

hash consistency when rook is (indirectly) exploded in atomic

---

src/main/scala/format/UciDump.scala
src/main/scala/variant/Variant.scala

FromPosition can have non-standard (Chess960) castling rights. So we have to use the more general Chess960 UCI notation for castling moves (or start to distinguish between standard and non-standard FromPosition).
Together with niklasf/fishnet@0ce633b037965b4ac016e126f2c8b006a164bc5b this fixes ornicar/lila#1132.

treat fromPosition as chess960 with regard to uci

---

src/main/scala/format/pgn/model.scala
src/test/scala/format/pgn/RenderTest.scala

The only suffixes allowed by the PGN standard are `!`, `?`, `!!`, `??`, `!?` and `?!`. But even so, NAGs are preferred for exporting [1].
(Not even scalachess can parse its own output like `1. e4??±→ Nf6`.)
[1] http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#AEN267

Render NAGs instead of unicode glyphs in PGNs

---

src/main/scala/Clock.scala

Set maxGraceMillis to 1000 so that lagging players aren't prematurely flagged.
maxGraceMillis should probably be at least as high as maxLagToCompensate.

Adjust maxGraceMillis

---

src/main/scala/Clock.scala

Change math to time / 8, min 10s, max 60s
- 1 0 game => 10s warning
- 2 0 game => 15s warning
- 10 0 game => 60s warning

Adjust emergency time cutoffs

---

src/main/scala/Clock.scala

Follow up from #77. The reason is as follows:
- The current math gives a higher alert for a game with
increment, i.e. 2 0 alerts at 15s, but 2 6 alerts at 45s.
Assuming the game has 10 moves left, the player in the 2 6
game actually has 105s left to finish. Even a 15s alert in
2 6 isn't nearly as dire as in 2 0.
- Simpler alert math is better because it is more intuitive
and predictable by users. In this spirit let's consider
removing the increment from the emerg cutoff calculation.

RFC: Ignore increment when calculating emerg alert

---

src/test/scala/format/pgn/RenderTest.scala

Regarding ornicar/lila#1942: The minimal problematic example gets rendered correctly from a handwritten PGN model. Problem must be before.

Test rendering PGN variations

---

src/main/scala/variant/Crazyhouse.scala

One side with more pieces than in the starting position is perfectly normal in crazyhouse. Just make sure both sides together are below the limit.

Fix crazyhouse board validation (fixes #86)

---

src/main/scala/variant/Crazyhouse.scala
src/main/scala/variant/ThreeCheck.scala

The new SF is sensitive to a missing +0+0 in threecheck fens.
```><> 1: DEBUG: Got job: {"work":{"type":"analysis","id":"Yxjn76nP"},"nodes":3500000,"game_id":"KzjTw1Fp","position":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","variant":"threeCheck","moves":"e2e4 e7e6 b1c3 f8b4 g1f3 g8f6 f1d3 c7c6 b2b3 d7d5 e4d5 f6d5 c1b2 b4c3 b2c3 d5c3 d2c3 d8f6 d1d2 b8d7 e1g1 b7b6 a1e1 c8b7 e1e6 f6e6 f1e1 e8c8 e1e6 f7e6 d2e2 h8e8 d3a6 c8c7 f3d4 c7b8 e2e5"}```
This leads to bugs like: https://de.lichess.org/forum/lichess-feedback/3-check-computer-analysis-not-giving-any-evals

provide initial fens with 3check and zh syntax

---

src/main/scala/variant/Horde.scala
src/test/scala/HordeVariantTest.scala

Lichess auto-drew in https://en.lichess.org/xQ2RsU8N#121 and this was wrong, black could capture it immediately. In fact, black always has the possibility to win {piece} vs K endgames, white can blunder it away. This means that scalachess must not ever auto-draw the game.

Fix horde auto-draw bug (lila#2552)

---

src/main/scala/format/Forsyth.scala
src/test/scala/format/ForsythTest.scala

useful for interoperability with winboard, cutechess and stockfish
corresponding lila issue: https://github.com/ornicar/lila/issues/2435
/cc @ddugovic, @rpdelaney

accept winboard-style zh pockets in fens

---

.travis.yml

The Slack token should have been encrypted. I revoked it and made a new one.

travis: fix slack token

---

src/main/scala/Actor.scala
src/main/scala/Role.scala
src/main/scala/variant/Variant.scala

It seems that `role.attacker` is only used in exactly these places. The filters unconditionally return true for kings, which is the only role where `attacker` was `false`.

simplify away Role.attacker

---

src/test/scala/ChessTest.scala
src/test/scala/DecayingStatsTest.scala

removed from scalalib here: https://github.com/ornicar/scalalib/commit/9e268452cfc77da54efb46b639e1cdf026e38bcf

switch to org.specs2.matcher.ValidationMatchers

---

src/main/scala/Centis.scala

It was only used in tests (now broken) and removed in 70ef53518c4db031ada25d7a16ada078db00756f. 
Most convenient would be to reintroduce it.

reintroduce Centis.abs to fix lila tests

---

src/main/scala/format/Forsyth.scala
src/main/scala/variant/Crazyhouse.scala
src/main/scala/variant/ThreeCheck.scala
src/test/scala/format/ForsythTest.scala

Scalachess can now parse winboard-style Crazyhouse and Three-Check FENs. The remaining question is: Should we switch completely? (https://github.com/ornicar/lila/issues/2435#issuecomment-266290903)

[RFC] switch to winboard fens

---

src/main/scala/DecayingStats.scala
src/main/scala/LagTracker.scala
src/test/scala/DecayingStatsTest.scala

- Using arithmatic averages instead of geometric for deviations, to be more
tolerant of lag spikes when producing estimations.
- Adjust quota start and max based on scaled quota gains.
This will defacto reduce lag comp for bullet games.

Update lag estimation

---

src/main/scala/Centis.scala
src/main/scala/Clock.scala
src/main/scala/DecayingStats.scala
src/main/scala/Game.scala
src/main/scala/LagTracker.scala
src/test/scala/ClockTest.scala
src/test/scala/DecayingStatsTest.scala

- Move clock logic from Game into Clock.
- Record avg lag comp and avg lag for reporting purposes.
- Avg lag comp will be stored in the new clock storage to improve
accuracy of game replay mode.
- Record lag metrics on move 1, so that clock delays are more
accurate and valid even for move 2.
- Use scalaz Monoid to simplify some code.

Rewrite and clean up Clock step

---

src/main/scala/LagTracker.scala
src/test/scala/ClockTest.scala

Some time controls reduced, such as ultra to .4 and hyper to .45.
Increase quota capacity based on graphana graphs which show players
sometimes spiking above the current quotas.

Reduce bullet lag comp

---

src/main/scala/variant/Variant.scala

Variant has only singletons for each type, we can speed up
equals with simple object equality.

Override Variant equals

---

src/main/scala/InsufficientMatingMaterial.scala
src/test/scala/VariantTest.scala

Short-circuit evaluation in my previous commit applied incorrectly: if I have bishops (or a bishop) and my opponent has no knights or pawns, then I win unless all bishops are on the same color square

Fix insufficient material check when both players have bishops

---

.travis.yml

I noticed were still testing on oraclejdk8. Might as well use what we're actually running on prod these days.

test on openjdk8

---

src/main/scala/variant/Antichess.scala

Someone made the comment to me that "reach a stalemate" means that "the stalemating player wins" rather than "the stalemated player wins". Although that's not how I ever interpreted it, he has a good point that it's not too clear. This edit removes any ambiguity from the title.

Re-word antichess "title"

---

src/main/scala/InsufficientMatingMaterial.scala
src/main/scala/StartingPosition.scala
src/main/scala/variant/Atomic.scala
src/main/scala/variant/Horde.scala
src/test/scala/AtomicVariantTest.scala
src/test/scala/AutodrawTest.scala

A player with only bishops can checkmate if the opponent has a knight (or a pawn), or if the position has bishops (of either color) on both color complexes.

Fix opposite-colored bishop with other pieces validation #163

---

src/main/scala/variant/Atomic.scala
src/test/scala/AtomicVariantTest.scala

Atomic helpmates by series of legal moves for K versus K+B+(B or N) of the same color are possible.

Atomic helpmate with bishop and knight of the same color is possible

---

src/main/scala/variant/Horde.scala
src/test/scala/HordeVariantTest.scala

As noted in https://lichess.org/forum/lichess-feedback/why-isnt-this-a-draw , there are some positions not currently detected as draws.  This patch seeks to handle pawnless draws where the non-horde player times out.
Also, if by some chance the horde underpromotes to 2+ same square-colored bishops (which a sane player is unlikely to do), now B+B is allowed to mate against K+N+N.  This code still does not attempt to detect draws for other unlikely "horde underpromoted" material configurations.

Horde often cannot mate with a lone bishop

---

src/main/scala/Board.scala
src/main/scala/History.scala
src/test/scala/AutodrawTest.scala
src/test/scala/CrazyhouseVariantTest.scala

Implementing a FIDE rule from 2018:
> 9.6 If one or both of the following occur(s) then the game is drawn:
> 9.6.1 the same position has appeared, as in 9.2.2 at least five times.
Unlike threefold repetition, fivefold does not need to be claimed.
Recent example: https://lichess.org/forum/lichess-feedback/perpetual-check-still-i-lost-the-game

auto draw on fivefold repetition

---

src/main/scala/Board.scala
src/main/scala/Situation.scala
src/main/scala/variant/Antichess.scala
src/main/scala/variant/Atomic.scala
src/main/scala/variant/Crazyhouse.scala
src/main/scala/variant/Horde.scala
src/main/scala/variant/KingOfTheHill.scala
src/main/scala/variant/RacingKings.scala
src/main/scala/variant/ThreeCheck.scala
src/main/scala/variant/Variant.scala
src/test/scala/AtomicVariantTest.scala
src/test/scala/AutodrawTest.scala
src/test/scala/CrazyhouseVariantTest.scala
src/test/scala/HordeVariantTest.scala
src/test/scala/VariantTest.scala

Same as #168, minus other refactorings, so hopefully easier to review. Clearly distinguishes:
* `isInsufficientMaterial`: Neither side can win. The game should end immediately.
* `opponentHasInsufficientMaterial`: Relevant when the side to move times out or disconnects.
Thanks @ddugovic for the original PR.

apply mating material check by situation (closes #168)

---

src/main/scala/StartingPosition.scala

Tidy up commit
I didn't notice that two other B01 openings were present when I added Icelandic-Palme variation in #191 
This commit updates the newly added Icelandic-Palme entry to look more like the two existing entries.
- Move Icelandic-Palme Gambit next to the other two B01 openings
- Update display name to match the other two B01 openings,
Old "Scandinavian Defense, Icelandic-Palme Gambit"
New "Scandinavian Defence: Icelandic-Palme Gambit"
- Update Wiki-link to Icelandic-Palme specific section (same section
as Modern)

Group Icelandic-Palme with existing B01 openings

---

src/main/scala/variant/Atomic.scala
src/test/scala/AtomicVariantTest.scala

Examples of positions in Atomic which are draws according to the FIDE rule of no legal move sequence to mate, but are not adjudicated as such by lichess: https://lichess.org/5HqshWY6#168 https://lichess.org/X4p7XV0s#91 https://lichess.org/VR3El4CK#80 These are not very rare, as leaving the extra opponent's bishop unable to capture your pawns is a recurring drawing idea in Atomic (see https://lichess.org/study/WOWizkm4). This is very annoying when happens, as everyone understands this is a dead draw where even stupid moves cannot lead to a win of either side.
This patch fixes these positions by using the following criteria (all must hold): 1) the sides have only kings, bishops and pawns 2) pawn structure is completely blocked - each pawn has no legal moves and is blocked by an opponent's …

Adjudicating Atomic positions with closed pawn structure and a pawnitized bishop as a draw

---

src/main/scala/StartingPosition.scala

This PR adds the Bird's Opening (1. f4) and Bird's Opening: Dutch Variation (1. f4 d5) to the list of available starting positions for tournaments. 
Ran into the unavailalbility during Chessweeb's stream where he tried to set up a Bird's Opening tournament.

Add Bird's opening to the tournament starting position list

---

src/main/scala/Drop.scala
src/main/scala/Move.scala
src/test/scala/AutodrawTest.scala

Fixes #203 
This PR uncomment a test that defines the issue and fixes it by adding one extra positionHash when it is the first move, namely, the hash of the current `Situation` (before the move, or, the initial position).
This was the chosen solution because the `positionHashes` is, in fact, a `Situation` hash. As a `Situation` depend on a `Board`, a `Board` depend on a `History` and we don't have the `History` yet when creating a `Game` then I chose to go the simplest way and add a conditional looking if it is the first move.
Also, it is important to note that the `Drop` class also changes the positionHashes in a similar way, but I did not really understood why. If this is important, the `Drop.finalizeAfter`must be changed too. I can do that if needed.
Lastly, I am not sure this will …

fix: threefold on initial position

---

src/main/scala/Actor.scala
src/main/scala/Board.scala
src/main/scala/Color.scala
src/main/scala/Divider.scala
src/main/scala/File.scala
src/main/scala/Hash.scala
src/main/scala/InsufficientMatingMaterial.scala
src/main/scala/Piece.scala
src/main/scala/Pos.scala
src/main/scala/Rank.scala
src/main/scala/Side.scala
src/main/scala/Situation.scala
src/main/scala/format/Forsyth.scala
src/main/scala/format/UciCharPair.scala
src/main/scala/format/Visual.scala
src/main/scala/format/pgn/Dumper.scala
src/main/scala/format/pgn/parsingModel.scala
src/main/scala/variant/Crazyhouse.scala
src/main/scala/variant/Horde.scala
src/main/scala/variant/RacingKings.scala
src/main/scala/variant/Variant.scala
src/test/scala/PerftTest.scala

a step towards #205
already proves quite useful because
```
(x: Int, y: Int) => Option[Pos]
```
but
```
(file: File, rank: Rank) => Pos
```

introduce rank and file types

---

src/main/scala/format/pgn/model.scala
src/test/scala/format/pgn/RenderTest.scala

removes the extra space before the result, if the game has no moves

fix result-only pgn rendering

---

src/main/scala/opening/FullOpeningPartC.scala

This is incorrectly called the Urusov Gambit when d4 / dxe4 haven't occurred.

Fix caption for Italian variation of Petrov

---

src/main/scala/opening/FullOpeningPartE.scala

Dzindzi-Indian Defense is already used to refer to the Beefeater. The proper name is [Dzindzikhashvili Defense](https://www.365chess.com/opening.php?m=7&n=9682&ms=d4.Nf6.c4.e6.Nf3.a6&ns=7.14.11.33.21.9682) according to ECO

Rename Dzindzi-Indian Defense to Dzindzikhashvili Defense

---

src/test/scala/format/pgn/Fixtures.scala
src/test/scala/format/pgn/ParserPerfTest.scala

This also enable `ParserPerfTest` when perform testing (removed `skipAll = true`). It just takes around 10 seconds so I don't think it is necessary to skip it.
I'll use results from this test to compare performance in #247.
I think it is better to use https://github.com/sbt/sbt-jmh or https://github.com/scalameter/scalameter. But after sort try I couldn't set them up. I'll probably try to work on that sometime in the future.
Update current output look like this in my machine (Macbook Pro 32GB ram, 2.6 GHz 6-Core Intel Core i7)
```
555 games in 328 ms
555 games in 331 ms
555 games in 287 ms
555 games in 293 ms
555 games in 283 ms
555 games in 333 ms
555 games in 281 ms
555 games in 282 ms
555 games in 281 ms
555 games in 277 ms
Average = 536 microseconds per game
1865 games per second
``` …

Use more games when perform ParserPerfTest

---

.gitignore
build.sbt
src/main/scala/format/pgn/Parser.scala
src/test/scala/format/pgn/ErrorMessagesTest.scala
src/test/scala/format/pgn/ParserTest.scala

This PR is for replacing `scala-parser-combinators` with `cats-parse`. The reason is mostly about performance but also it'll be easier to read and maintain (no more regex).
TODO

Reimplement pgn parser by using cats-parse

---

src/main/scala/format/pgn/Parser.scala
src/test/scala/format/pgn/ErrorMessagesTest.scala
src/test/scala/format/pgn/Fixtures.scala

Close #253 
Below  is sample of error messages:
Example 1:
```
[ab "cdef"]     [123]
1. e4 { hello world }  c5??
2. c6
```
Error:
```
Cannot parse tags: [1.17]: Tag name can only contains alphabet characters
[ab "cdef"]    [123]
^
[ab "cdef"]    [123]
```
Example 2:
```
[ab "cdef]
1. e4 { hello world }  c5??
2. c6
```
Error:
```
Cannot parse tags: [1.11]: expected: "
[ab "cdef] 
^
[ab "cdef]
```
performance is also improved
```
55 games in 22 ms
55 games in 20 ms
55 games in 20 ms
55 games in 19 ms
55 games in 19 ms
55 games in 19 ms
55 games in 18 ms
55 games in 23 ms
55 games in 20 ms
55 games in 16 ms
Average = 356 microseconds per game
2808 games per second
```

Reject files that havve invalid tags

---

src/main/scala/Game.scala

If clock is not available, it's not necessary to perform relatively expensive evaluation of situation status.
Before:
```
sbt:scalachess> testOnly shogi chess.ReplayPerfTest
running tests
500 games in 3611 ms
500 games in 3491 ms
500 games in 3792 ms
500 games in 3448 ms
500 games in 3671 ms
Average = 7205 microseconds per game
138 games per second
[info] ReplayPerfTest
[info] playing a game should
[info]   + many times
[info] Total for specification ReplayPerfTest
[info] Finished in 24 seconds, 918 ms
[info] 1 example, 0 failure, 0 error
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
```
After:
```
sbt:scalachess> testOnly shogi chess.ReplayPerfTest
running tests
500 games in 1352 ms
500 games in 1276 ms
500 games in 1222 ms
500 games in 1186 ms
500 games in 1181 ms
Average = 2486 …
```

Evaluate situation.status only when we actually have clock

---

src/main/scala/format/pgn/Parser.scala

Before we converted result string to `Tag` after parsing. Which is not necessary also makes the code looks ugly. Not we only created Result Tag when it is needed.

Stop converting result to Tag after parsing

---

src/main/scala/format/pgn/Parser.scala
src/test/scala/format/pgn/ParserTest.scala

Close #255 also improve performance of parser
Refactor to remove global string replacement ( except the one for pgn writer comment %)
Side effect of this change:
Performance is a bit improved
```
55 games in 27 ms
55 games in 26 ms
55 games in 21 ms
55 games in 42 ms
55 games in 20 ms
55 games in 18 ms
55 games in 18 ms
55 games in 18 ms
55 games in 17 ms
55 games in 19 ms
Average = 410 microseconds per game
2439 games per second
```
Error messages can show the location of the error in the whole string (not in splited string as before)
Example:
```
Cannot parse pgn: [4.4]: Invalid chess move
2. bla
^
[abc "def"]
1. e4 { hello world } Nc6
2. bla
```

Simplify parser code

---

src/main/scala/opening/FullOpeningPartD.scala

I've never heard anyone before call this opening Mason Variant, everyone
is just calling it a variant of London System.
some examples:
wikibooks uses Accelerated London System:
https://en.wikibooks.org/wiki/Chess_Opening_Theory/1._d4/1...d5/2._Bf4
wikipedia uses Modern London System:
https://en.wikipedia.org/wiki/London_System#The_Modern_London
chess.com uses Accelerated London System:
https://www.chess.com/openings/Queens-Pawn-Opening-Accelerated-London-System
I also had a look in Lichess studies and studies explaining 1. d4 d5 2. Bf4
are usually referring to London System, I found just one study that explained
this opening and was named "Mason Variant".
Therefore, this commit proposes to change the name of this opening from:
Queen's Pawn Game: Mason Variation
to:
Queen's Pawn Game: …

rename Queen's Pawn Game: Mason Variant to Accelerated London System

---

src/main/scala/variant/Antichess.scala
src/test/scala/AntichessVariantTest.scala

The change solves issue #296 by implementing the `opponentHasInsufficientMaterial` method. The implementation resembles the implementation of the `isInsufficientMaterial` method.

Antichess insufficient material

---

src/main/scala/format/pgn/Binary.scala

After applying the inline keyword and "fixing" the compile error in #305, it used Byte.toInt instead of Binary.toInt in the mapping method, causing BinaryTest to fail. Hence, I've made it more explicit. Bit more verbose now, but I can't pass it as a function since it's inline.
My bad.

Scala3 - Fix for BinaryTest

---

src/main/scala/format/pgn/Dumper.scala
src/test/scala/format/pgn/DumperTest.scala

See https://github.com/lichess-org/lila/issues/11659 for background.
Note that this will update behaviour for standard games and all variants, such that all games that end with a winner defined will have the final move appended with `#`. I'm not sure if this is desired behaviour, or if we only want to fix the "three checks" variant. If we want to limit the blast radius a bit, another approach could be to update the conditional logic to only append `#` in the case where `next.winner.isDefined` and `next.check` are both true (solving the "three checks" problem with less potential for unforeseen/undesirable `#` annotations in other games).

Update pgn for three check winning move

---

build.sbt
src/main/scala/Castles.scala
src/main/scala/History.scala
src/main/scala/bitboard/Board.scala
src/test/scala/ChessTest.scala
src/test/scala/HistoryTest.scala
src/test/scala/PawnTest.scala
src/test/scala/format/Visual.scala

This is to enforce clients (lila) initiate `UnmovedRooks`. scalachess now depends on the correctness of `UnmovedRooks` to generate castling moves.

 Remove default value for UnmovedRooks

---

src/main/scala/Situation.scala
src/test/scala/ReplayTest.scala

Fixes lichess-org/lila#12206
We want castling to always use 960 notation so that we can just compare uci to check whether it's the same move. Since the representative move is just the first one found (https://github.com/lichess-org/scalachess/blame/master/src/main/scala/format/pgn/parsingModel.scala#L132), make sure that the first one is the 960 move (i.e. where the king moves onto the rook).
Doesn't really feel like a super solid solution but I guess it's also how it worked before:
- https://github.com/lichess-org/scalachess/blob/a44879b2ae9deaa94b887a2df0b5912c55752304/src/main/scala/Actor.scala#L136
- https://github.com/lichess-org/scalachess/blob/a44879b2ae9deaa94b887a2df0b5912c55752304/src/main/scala/format/pgn/parsingModel.scala#L135

Make castling uci always 960 notation

---

src/test/resources/chess960.perft
src/test/scala/perft/Perft.scala
src/test/scala/perft/PerftTest.scala

Add more perf tests from
- https://www.chessprogramming.org/Chess960_Perft_Results
- https://github.com/AndyGrant/Ethereal/blob/master/src/perft/fischer.epd

Add more perft tests for Chess960 castles

---

src/main/scala/Castles.scala
src/main/scala/Situation.scala
src/main/scala/UnmovedRooks.scala
src/main/scala/bitboard/OpaqueBitboard.scala
src/main/scala/variant/Atomic.scala
src/main/scala/variant/KingOfTheHill.scala
src/main/scala/variant/RacingKings.scala
src/main/scala/variant/Variant.scala
src/test/scala/bitboard/Fen.scala
src/test/scala/bitboard/OpaqueBitboardTest.scala

We use `(a & b).nonEmpty` or `(a & b).isEmpty` in several places.
So they're deserve an abstraction in `OpaqueBitboard`.
I named them `sharedAny` and `sharedNone` respectively, but not sure they're the best.
Welcome any naming suggestion.

Add sharedAny and sharedNone for Bitboard

---

build.sbt
src/main/scala/Game.scala
src/main/scala/MoveOrDrop.scala
src/main/scala/Replay.scala
src/main/scala/format/Uci.scala
src/main/scala/format/UciDump.scala
src/main/scala/format/pgn/parsingModel.scala
src/main/scala/opening/OpeningDb.scala
src/main/scala/package.scala
src/test/scala/DividerTest.scala
src/test/scala/format/pgn/ReaderTest.scala

Refactor `type MoveOrDrop = Either[Move, Drop]` to `type MoveOrDrop = Move | Drop`.

MoveOrDrop as union type & bump version 14.5.0

---

bench/src/main/scala/benchmarks/ParserBench.scala
bench/src/main/scala/benchmarks/PerftBench.scala
bench/src/main/scala/benchmarks/PlayBench.scala
src/main/scala/Castles.scala
src/main/scala/Situation.scala
src/main/scala/UnmovedRooks.scala
src/main/scala/bitboard/OpaqueBitboard.scala
src/main/scala/variant/Atomic.scala
src/main/scala/variant/KingOfTheHill.scala
src/main/scala/variant/RacingKings.scala
src/main/scala/variant/Variant.scala
src/test/scala/bitboard/Fen.scala
src/test/scala/bitboard/OpaqueBitboardTest.scala

Did run benchmarking and the result is as @niklasf predicted, `sharedAny` and `sharedNone` are much slower than `&`.
Here is the benchmark result: https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/e5b1eb149ccbbea7b4b9a928f4194fdf/raw/57eca9c682ff40887ac4127777f8badf51558bfd/master-230218.json,https://gist.githubusercontent.com/lenguyenthanh/e5b1eb149ccbbea7b4b9a928f4194fdf/raw/57eca9c682ff40887ac4127777f8badf51558bfd/intersects.json

Use intersects/isDisjoint instead of sharedAny/sharedNone

---

src/main/scala/Board.scala
src/main/scala/Pos.scala
src/main/scala/bitboard/Board.scala
src/main/scala/variant/Atomic.scala
src/test/scala/AtomicVariantTest.scala

More improvements for Atomic exploding and `bitboard.Board.discard` function.
Here is the [benchmark result](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/ea7f027f5aef45fe6716ba26cc535fa5/raw/f15cc416cd8feb964469c70a761dc2885a18b8cb/master-aeb00a0.json,https://gist.githubusercontent.com/lenguyenthanh/ea7f027f5aef45fe6716ba26cc535fa5/raw/f15cc416cd8feb964469c70a761dc2885a18b8cb/atomic.json) against current master.

Improve atomic's exploding with bitboard

---

src/main/scala/variant/Horde.scala
src/test/scala/HordeVariantTest.scala

Reported by https://lichess.org/forum/lichess-feedback/horde-game-declared-a-draw-moves-still-possible
And thanks @370417 for the test and investigation.
I did cause this bug via: #372, specially these lines: https://github.com/lichess-org/scalachess/blob/master/src/main/scala/variant/Standard.scala#L23-L24
There is a hidden breaking changes in moves generator. Not it requires the King on the board in order to generate legal moves (which is makes sense imho). But that created the current bug.
Previously, in [hordeClosedPosition](https://github.com/lichess-org/scalachess/pull/375/commits/ed4707cbd305fa3b8fa1763de15e150710d00a35#diff-68b609c46c14d44b7611d95a53be1a8ebefb9c5bff8ef449ef42cfdc15669709R51) function, it removes the King from the board and then tries to generate legalMoves, which …

Horde: Black insufficient material bug

---

build.sbt
src/main/scala/Piece.scala
src/main/scala/Replay.scala
src/main/scala/bitboard/OpaqueBitboard.scala
src/main/scala/format/pgn/parsingModel.scala
src/test/scala/AntichessVariantTest.scala
src/test/scala/ReplayTest.scala
src/test/scala/bitboard/OpaqueBitboardTest.scala
src/test/scala/format/pgn/ParserTest.scala

- For Std San: When trying to find the correct moves, traverse only relevant pieces instead of all pieces. Also return result immediately after find the correct move.
- For Castle: Generate only castling moves instead of all legal moves.
- Opaque type for Sans
- Bump 14.5.6
benchmark results: https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/ea7f027f5aef45fe6716ba26cc535fa5/raw/9651d5b58c900cddbe5b60f87faa06b00c2c9d48/master-e422d2d.json,https://gist.githubusercontent.com/lenguyenthanh/ea7f027f5aef45fe6716ba26cc535fa5/raw/971d160c3dc37c9c02203cc74d13f307a1a755a7/replay-2.json

Optimize replay & Opaque type for Sans & Bump 14.5.6

---

src/main/scala/Castles.scala
src/main/scala/InsufficientMatingMaterial.scala
src/main/scala/Situation.scala
src/main/scala/UnmovedRooks.scala
src/main/scala/bitboard/Bitboard.scala
src/main/scala/bitboard/Board.scala
src/main/scala/bitboard/OpaqueBitboard.scala
src/main/scala/format/FenReader.scala
src/main/scala/variant/Antichess.scala
src/main/scala/variant/Crazyhouse.scala
src/main/scala/variant/Standard.scala
src/test/scala/AtomicVariantTest.scala
src/test/scala/UnmovedRooksTest.scala
src/test/scala/bitboard/OpaqueBitboardTest.scala

Some minor simplify and cleanup `OpaqueBitboard`, to make it's API more consistent
- Move apply(List[Post]) to OpaqueBitboard
- Refactor `OpaqueBitboard`: `occupiedSquares` => `squares`
- Refactor `OpaqueBitboard`: `addPos` => `addSquare`
I believe we should Refactor `Pos` to `Square` in future to make scalachess more consistent with our other chess libraries. But it can be in another PR when we decide to break things to have better API.

Some minor simplify and cleanup OpaqueBitboard API

---

src/main/scala/Board.scala
src/main/scala/Piece.scala
src/main/scala/bitboard/Board.scala
src/main/scala/format/pgn/Dumper.scala
src/main/scala/format/pgn/parsingModel.scala
src/test/scala/bitboard/BitboardTest.scala

Improve Dumper implementation by only traverse the moving pieces instead of the all pieces. This also fix the broken `Piece.eyes` function. So this should improve our `ReplayBench` quite a bit. Will Run benchmark and post here when I have time.

Improve Dumper

---

src/main/scala/variant/Horde.scala
src/test/scala/HordeVariantTest.scala

Fix for this game: https://lichess.org/VS6zKkgr#103.
In this game, White is currently stalemated, and Black can only move the King. But after the King moved, White is not stalemated anymore.
I fixed it by verifying after every valid Black's King move, White is still stalemated. So this will be more expensive than before. I hope that it's rarely happen.

Fix horde insufficient material

---

bench/src/main/scala/benchmarks/HashBench.scala
src/test/scala/format/pgn/Fixtures.scala

There were two partial pgn files in the test fixtures, so it's always failed during the replay phase, and throw exceptions. This fixed by remove pgn: festivalFigueira and crazyhouseNoVariantTag. This also tries to improve the accuracy of HashBench.

Fix HashBench

---

src/test/scala/perft/FullPerftTest.scala

Now the CI usually takes 30-40 minutes to finish - most of the time is for the `perft` tests.
It is okay, but a bit annoying to wait, especially when you don't touch move generator part.
This PR is to reduce the number of `nodeLimits` from 10M to 1M. Which in turn will reduce significant CI time.
I also have a project which exist for the pure purpose of testing scalachess here: https://github.com/lenguyenthanh/scalachess-tests, I bump the scalachess version occasionally to make sure `scalachess` behaves correctly.

Reduce number of nodeLimits to reduce CI time

---

src/main/scala/format/pgn/Parser.scala
src/main/scala/format/pgn/Pgn.scala
src/main/scala/format/pgn/model.scala
src/main/scala/format/pgn/parsingModel.scala
src/test/scala/format/pgn/RenderTest.scala
src/test/scala/format/pgn/RoundtripTest.scala

- Rename `InitialPosition` => `InitialComments`
- Reuse `InitialComments` for `Pgn`

Refactor initial position

---

src/main/scala/Hash.scala
src/main/scala/InsufficientMatingMaterial.scala
src/main/scala/Situation.scala
src/main/scala/bitboard/Board.scala
src/main/scala/bitboard/OpaqueBitboard.scala
src/main/scala/format/pgn/Dumper.scala
src/main/scala/format/pgn/Glyph.scala
src/main/scala/variant/Crazyhouse.scala
src/main/scala/variant/Standard.scala
src/test/scala/AtomicVariantTest.scala
src/test/scala/bitboard/Arbitraries.scala
src/test/scala/bitboard/BitboardTest.scala
src/test/scala/bitboard/OpaqueBitboardTest.scala

Add more helper functions for `OpaqueBitboard`, such as: `map`, `filter`, `forall`. So, we don't need to do something like `bitboard.squares.forall` anymore, we can just do `bitboard.forall` directly.
Also with these functions, we can obmit bb.squares in for comprehension.

Improve OpaqueBitboard

---

src/main/scala/bitboard/OpaqueBitboard.scala

This is justifiable, because it's a private function, and we only use it after checking the bitboard is not empty.

Make lsb returns Square directly

---

src/main/scala/Board.scala
src/main/scala/ByColor.scala
src/main/scala/Divider.scala
src/main/scala/Game.scala
src/main/scala/Hash.scala
src/main/scala/Role.scala
src/main/scala/bitboard/Board.scala
src/main/scala/variant/Antichess.scala
src/main/scala/variant/Variant.scala

https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/d68ee24651bf8bcadc136c7a758ada2b/raw/c926060cf41cd157aeb1423c9849f874739aab37/master-4b4c3.json,https://gist.githubusercontent.com/lenguyenthanh/f4fb81fd376e2949bf3df633fee312de/raw/9b92f3b20f768cbe24ffb445b3af5c129309b554/final.json

Fix recent regression

---

src/main/scala/Divider.scala

Before:
```
[info] PlayBench.divider  thrpt   45  21.868 ± 1.357  ops/s
```
After, first attempt:
```
[info] PlayBench.divider  thrpt   45  33.767 ± 1.497  ops/s
```
Additionally, precomputing mixedness regions again:
```
[info] PlayBench.divider  thrpt   45  51.566 ± 4.220  ops/s
```
Additionally, using `mapReduce`:
```
[info] PlayBench.divider  thrpt   45  65.580 ± 3.128  ops/s
```
Additionally, using `Long` instead of `Bitboard` region masks:
```
[info] PlayBench.divider  thrpt   45  91.231 ± 5.867  ops/s
```

optimize Divider.mixedness

---

src/main/scala/ByColor.scala
src/test/scala/ByColorLawsTests.scala
src/test/scala/ByColorTest.scala

benchmarks code:
```scala
package benchmarks
import org.openjdk.jmh.annotations.*
import org.openjdk.jmh.infra.Blackhole
import java.util.concurrent.TimeUnit
import chess.ByColor
@State(Scope.Thread)
@BenchmarkMode(Array(Mode.Throughput))
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@Measurement(iterations = 15, timeUnit = TimeUnit.SECONDS, time = 3)
@Warmup(iterations = 15, timeUnit = TimeUnit.SECONDS, time = 3)
@Fork(value = 3)
@Threads(value = 1)
class ByColorBench:
// the unit of CPU work per iteration
private[this] val Work: Long = 10
case class Game(pgn: String)
var byColor: ByColor[Game] = _
var byColorO: ByColor[Option[Game]] = _
def f(s: String): Option[String] =
if s.size % 3 == 0 then None
else Some(s)
@Setup
def setup() =
byColor = ByColor(Game("foo"), Game("bar"))
byColorO = …
```

Optimize ByColor flatMap/flatten

---

src/main/scala/bitboard/Board.scala

Another optimization with the price of duplicated code. The result is below, but lets talk about why this is better. Generics is awesome in general, but it's quite bad for performance. It's required allocation and boxing when working with primitive. In our case ByColor[Bitboard] will required 2 extra allocations, which is not much but still 🤷 .
Another thing is about `Monomorphic` and `megamorphic` 🤯 , which this [article](https://gist.github.com/djspiewak/464c11307cabc80171c90397d4ec34ef) and its reference are really good sources.
Some code for the demonstration:
```scala
//> using scala 3.3.0
package example
object Main:
val b1 = ByColorG(Bitboard(1))
val b2 = ByColor(Bitboard(1))
def main(args: Array[String]): Unit =
println(b1)
println(b2)
case class ByColorG[T](x: T)
case class …
```

Specialize ByColor & ByRole for bitboard.Board

---

build.sbt

It works, I use `javap -verbose target/scala-3.3.0/classes/chess/Color.class` to verify. We can see the major versions has changed from `56` (jdk 12) to `61` jdk 17. We currently use `"-Xtarget:12"`.
```
Before
minor version: 0
major version: 56
After:
minor version: 0
major version: 61
```

Produce bytecode version 17

---

README.md

- lichess-org org
- default to https so non-members can clone

Update repo url in readme

---

bench/src/main/scala/benchmarks/HashBench.scala
src/main/scala/Drop.scala
src/main/scala/Hash.scala
src/main/scala/History.scala
src/main/scala/Move.scala
src/main/scala/format/FenReader.scala
src/test/scala/ChessTest.scala
src/test/scala/HistoryTest.scala

Before
```
[info] HashBench.hashes       thrpt   45  746.230 ± 15.666  ops/s
[info] HashBench.repetition3  thrpt   45  709.714 ± 26.750  ops/s
[info] HashBench.repetition5  thrpt   45  808.189 ± 32.930  ops/s
```
After removing newtypes & change algorithm
```
[info] HashBench.hashes       thrpt   45    748.412 ±  19.580  ops/s
[info] HashBench.repetition3  thrpt   45  12099.058 ± 232.333  ops/s
[info] HashBench.repetition5  thrpt   45  12276.818 ± 187.127  ops/s
```
Removing Monoid
```
[info] HashBench.hashes       thrpt   45    758.422 ±  33.644  ops/s
[info] HashBench.repetition3  thrpt   45  12476.803 ± 114.103  ops/s
[info] HashBench.repetition5  thrpt   45  12865.016 ± 195.063  ops/s
```
[Full benchmark](https://gist.github.com/lenguyenthanh/9380c5422ca40efedb567c32de1f4793)

Optimize Hash and isRepetition function

---

bench/src/main/scala/benchmarks/PgnBench.scala
src/main/scala/Castles.scala
src/main/scala/format/pgn/Pgn.scala
src/test/scala/format/pgn/PgnHelper.scala
src/test/scala/format/pgn/RenderTest.scala

Optimize `Pgn.render` by using `StringBuilder`. ~This improved speed twice, but still keep using recursion for rendering. That means we can have potential stacksafe issue (I don't see stackoverflow up to 20k nodes). I'll work on that later.~
Edit: Actually we already can have some `tailrec` after all, profiler before/after.
Before
```
[info] PgnBench.pgnRender  thrpt   45  342.884 ± 2.720  ops/s
```
After StringBuilder
```
[info] PgnBench.pgnRender  thrpt   45  760.030 ± 17.521  ops/s
```
After `tailrec`:
```
[info] PgnBench.pgnRender  thrpt   45  764.908 ± 2.781  ops/s
```
[Full benchmark](https://gist.github.com/lenguyenthanh/68f79c29eecdd7f45103d4b8cdf17c9f)

Optimize pgn render

---

src/main/scala/Drop.scala
src/main/scala/Game.scala
src/main/scala/Move.scala
src/main/scala/MoveOrDrop.scala

Have this idea, while reading: https://github.com/lichess-org/lila-ws/blob/master/src/main/scala/Chess.scala#L22-L25
In that function, `game.sans.lastOption` check  is unnecessary, because we we have the move, that is the evidence of `game.sans.last` cannot be `None`. But we have to do that check anyway, because the type system doesn't know `game.sans.last` is non empty.
This pr is to solved this problem, by adding `san` as a `lazy val` for both `Move` and `Drop`, so that we can access `san` whenever we have `MoveOrDrop`, without asking the `game.sans`. And also avoid re-computation of `san` when possible.

Add `lazy val san: SanStr` for Move and Drop

---

src/main/scala/Drop.scala
src/main/scala/Move.scala

In some highly concurrent situation, lazy vals introduced in #466 causes deadlocks: https://github.com/lenguyenthanh/scalachess-tests/actions/runs/5766743713/job/15704620174
I still don't know the root cause of it, but this is fixed it (tested locally).

Fix deadlock because of lazy vals

---

src/main/scala/Move.scala
test-kit/src/test/scala/PlayTest.scala

Resolves https://github.com/lichess-org/lila/issues/13452

Only update castle rights when the rook involved can castle

---

src/main/scala/Replay.scala

- Fix reversed order when error happen
- Add gameMoveWhileValidReverse because in some case we need
games in reverse order, for example: https://github.com/lichess-org/lila/blob/27f1db88d269c17a04ccdbdfa67ed9cda6bd4514/modules/study/src/main/ServerEval.scala#L147
- This is a bit slower than the previous implementation but I guess only in micro benchmark settings. The new implementation looks nicer and can short circuit when error happen.

Traverse sans only once in gameMoveWhileValid

---

src/main/scala/Situation.scala
src/main/scala/bitboard/Bitboard.scala
test-kit/src/test/scala/CastlingTest.scala
test-kit/src/test/scala/bitboard/BitboardTest.scala

Add add `removeLast` function for Bitboard, which I though I'm gonna use for this fix but end up with another solution in the end.

Fix generating castlings when unmoved rooks and castles are inconsistent

---

src/main/scala/format/Fen.scala
test-kit/src/test/scala/format/SmallFenTest.scala

This happen when in White's turn, and there is a enpassant on b6.
Before this fix, it is mistaken the b from b6 as Black's turn. So,
the fix is make sure that only set black turn if there is no number
after character b.

Fix small test conversion

---

src/main/scala/Hash.scala
test-kit/src/test/scala/CrazyhouseVariantTest.scala
test-kit/src/test/scala/HashTest.scala

This only happen in custom positions when there 
are too much materials. The fix is return None when
IndexOutOfBound happen, this will increase the
risk of collusion but the positions are invalid
in this case anyway.
This is an effort to remove the try catch in lila-ws
https://github.com/lichess-org/lila-ws/blob/a3f2d9ab3ec573e07ff05eb1e7db38d93e27e2da/src/main/scala/Chess.scala#L26

Fix IndexOutOfBound when hashing Crazyhouse variant

---

.github/dependabot.yml

Automatically create update PRs for Github Actions workflows, like `actions/checkout` or `actions/setup-java`.
To avoid update spam, only updates them once a month & groups the updates into one pull request. Simply stops the actions versions from growing old.
There already are some older action versions in use, causing warnings in CI runs like:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20 [...]
To see sample PR generated by merging of this config, [see this PR in my fork.](https://github.com/stscoundrel/scalachess/pull/2)

Add Dependabot updates to Github Actions dependencies

---

bench/src/main/scala/benchmarks/BinaryFenBench.scala
src/main/scala/Rank.scala
src/main/scala/Square.scala
src/main/scala/bitboard/Bitboard.scala
src/main/scala/format/BinaryFen.scala
src/main/scala/format/FenWriter.scala
test-kit/src/test/scala/format/BinaryFenTest.scala

* Information stored: Complete FEN (including move numbers, position not necessarily legal, invalid castling rights / ep may be lost) + variant
```
Situation.AndFullMoveNumber <=> Array[Byte]
```
* Relatively compact packing (but still further compressible with entropy coding). Examples:
fen | EpdFen | SmallFen | BinaryFen
--- | --- | --- | ---
rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1 | 58 bytes | 43 bytes | 24 bytes
QN4n1/6r1/3k4/8/b2K4/8/8/8 b - - 0 1 | 36 bytes | 20 bytes | 12 bytes
* Main part of the encoding adapted from https://github.com/official-stockfish/nnue-pytorch/blob/master/lib/nnue_training_data_formats.h#L4607.
* Move numbers not needed? The default of `0 1` is particularly efficient.
* Quite fast:
- order of 5 million reads / second
- order of 3 million …

Implement reasonably fast and compact BinaryFen

---

test-kit/src/test/scala/CastlingTest.scala
test-kit/src/test/scala/PawnTest.scala

In test output, there were some confusing "duplicated" test cases being run. Upon closer inspection they were not duplicates, but their names were somewhat misleading.
- Castling tests: there was duplicate "queen side" test, where the other was in fact "king side" test incorrectly named
- Pawn tests: there was "duplicate" for every test, but apparently first ones were white pawn tests and latter ones black pawn tests. Rename them to give clear output which one is being tested.
While checking these, I also added additional castling tests. Nothing of note was revealed through them, but adds a bit of coverage for different scenarios.
- Bishop variant of threat. Sibling to current knight/rook tests.
- Threat on rooks trip during castling move.

Additional castling tests & test name cleanup

---

bench/src/main/scala/benchmarks/PgnBench.scala
core/src/main/scala/format/pgn/Pgn.scala
core/src/main/scala/format/pgn/PgnNodeEncoder.scala
core/src/main/scala/format/pgn/parsingModel.scala
test-kit/src/main/scala/chess/ChessTreeArbitraries.scala
test-kit/src/test/scala/format/pgn/RoundtripTest.scala

If the We have the tree and a starting ply, then We don't really need Ply
for each pgn node. We can increment ply when traversing the tree. This
will reduce the complexity for generating PGN from other structure as We
don't have to increment ply when generating PgnNodeEncoder. This also
give us an option to not include turn number in pgn.
[benchmark](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/44d2df060d6cab4c9deebef0c18df4aa/raw/88a982f1b1cfbb170e78e078849d95b6365d47fe/before.json,https://gist.githubusercontent.com/lenguyenthanh/44d2df060d6cab4c9deebef0c18df4aa/raw/88a982f1b1cfbb170e78e078849d95b6365d47fe/after3.json) show a bit of improvement as well

Simplify PgnNodeEncoder Trait

---

core/src/main/scala/LagTracker.scala

Lag comp quota is intended to build up each turn so that it can be used for spikes.  The current code depletes quota on slow computers, and even for computers with cpu lag below .04s, quota builds too slowly to be able to be used for multiple spikes in a game.
This patch is intended to be a short term fix, with a significant code and documentation overhaul planned in the near future.

Restore lag comp quota behavior

---

build.sbt
test-kit/src/main/scala/chess/pgn.scala
test-kit/src/test/scala/format/pgn/MacrosTest.scala

I put it in testKit for now, as I don't see using it in prod. But could be useful for testing.
the usage is in the tests:
```scala
import macros.*
test("pgn macro"):
val pgn = pgn"1. e4 e5 2. Nf3 Nc6" // We validate this at compile time.
assert(pgn.tree.isDefined)
assertEquals(pgn.toPgn.toString, "1. e4 e5 2. Nf3 Nc6")
```

Implement literal pgn

---

core/src/main/scala/Hash.scala
test-kit/src/test/scala/HistoryTest.scala

for compatibility with lichess-org/compression
fix [#16317](https://github.com/lichess-org/lila/issues/16317)

throw away lsb rather than msb of position hashes

---

bench/src/main/scala/benchmarks/PerftBench.scala
core/src/main/scala/Square.scala
core/src/main/scala/bitboard/Attacks.scala
core/src/main/scala/bitboard/Magic.scala

Using [`@static` annotation](https://docs.scala-lang.org/sips/static-members.html) to compile all `private val` field as `static` field. The benchmark is staying the same or increasing so little probably because jit inlines those functions anyway. But lets do this to avoid any doubt. 
here is the decompiled code before and after the change:
before:
```java
public final class Attacks {
public static long[] ATTACKS() {
return Attacks$.MODULE$.ATTACKS();
}
public static long[][] BETWEEN() {
return Attacks$.MODULE$.BETWEEN();
}
public static long[] BLACK_PAWN_ATTACKS() {
return Attacks$.MODULE$.BLACK_PAWN_ATTACKS();
}
public static long[] FILES() {
return Attacks$.MODULE$.FILES();
}
public static long[] KING_ATTACKS() {
return Attacks$.MODULE$.KING_ATTACKS();
}
public static long[] …
```

Use static annotation to optimize Bitboard Magic and Attacks

---

core/src/main/scala/StartingPosition.scala

This used to be known as "Nimzo-Indian Defense: Sämisch Variation, Accelerated" but was removed from the openings db in https://github.com/lichess-org/chess-openings/pull/219.
This starting position therefore now resolves to an empty optional and isn't actually used.
Side note: This actually caused the order of all the daily opening tournaments to be reshuffled completely.

Remove non-existent opening from starting positions

---

core/src/main/scala/StartingPosition.scala
test-kit/src/test/scala/opening/StartingPositionTest.scala

This will crash instead of silently ignore faulty starting positions. Which is safe as we also add tests to guard against those cases.
Related to #638

Use sequence.get instead of flatten for StartingPosition

---

bench/src/main/scala/benchmarks/BinaryFenBench.scala
bench/src/main/scala/benchmarks/PgnBench.scala
core/src/main/scala/Replay.scala
core/src/main/scala/format/pgn/Parser.scala
core/src/main/scala/format/pgn/Reader.scala
core/src/main/scala/format/pgn/parsingModel.scala
test-kit/src/test/scala/format/pgn/ParserCheck.scala
test-kit/src/test/scala/format/pgn/ParserTest.scala

Add two new function to `pgn.Parser`: `mainline` and `mainlineWithMetas`, both are only parse mainline of the input (a.k.a ignoring all variations). Which provides somewhat better performance and leaner data structure for consumers.
This also:
- Adapt `Reader` to use `Parser.mainline`
- Rename `Parser.sanOnly` to `Parser.san` to make it more simple and more fit with the other functions: `full`, `move`, `mainline`.
`mainline` is 20% faster than `full` with mixed pgn inputs:
```
[info] Benchmark                             Mode  Cnt    Score   Error  Units
[info] PgnBench.pgnFullParser               thrpt   45   94.473 ± 0.329  ops/s
[info] PgnBench.pgnMainlineWithMetasParser  thrpt   45  107.413 ± 0.390  ops/s
[info] PgnBench.pgnMainlineParser           thrpt   45  113.836 ± 0.503  ops/s …
```

Add `mainline` and `mainlineWithMetas` to pgn.Parser

---

core/src/main/scala/format/pgn/Parser.scala
test-kit/src/test/scala/format/pgn/ParserTest.scala

Would be useful for this: https://github.com/lichess-org/lila/blob/62137a34043da1e869c38eecf75916d1dbdf7f22/modules/study/src/main/ExplorerGame.scala#L58
As it can be refactored as follow:
```diff
private def gameTitle(g: Game): String =
-    val pgn = g.pgnImport.flatMap(pgnImport => Parser.full(pgnImport.pgn).toOption)
-    val white =
-      pgn.flatMap(_.tags(_.White)) | namer.playerTextBlocking(g.whitePlayer)(using lightUserApi.sync)
-    val black =
-      pgn.flatMap(_.tags(_.Black)) | namer.playerTextBlocking(g.blackPlayer)(using lightUserApi.sync)
+    val tags = g.pgnImport.flatMap(pgni => Parser.full(pgni.pgn).toOption).map(_.tags).getOrElse(Tags.empty)
+    gameTitle(g, tags)
+
+  private def gameTitle(g: Game, tags: Tags): String =
+    val white  = tags(_.White) | …
```

Implement pgn.Parser.tags to parse tags

---

core/src/main/scala/Replay.scala
core/src/main/scala/bitboard/Board.scala
core/src/main/scala/format/pgn/Parser.scala
core/src/main/scala/format/pgn/Reader.scala
core/src/main/scala/format/pgn/parsingModel.scala
core/src/main/scala/variant/Variant.scala

For pgn parser: the error of the pgn from https://lichess.org/forum/lichess-feedback/cant-parse-a-pgn will be: `Error parsing PGN: Invalid chess move at line 1, column 1792`
For `replay`, exclude `Situation` from error and some minor improvement.

Improve some error messages

---

core/src/main/scala/format/pgn/Parser.scala
core/src/main/scala/format/pgn/Reader.scala
core/src/main/scala/format/pgn/parsingModel.scala
test-kit/src/test/scala/format/pgn/ParserTest.scala
test-kit/src/test/scala/format/pgn/PgnRenderTest.scala
test-kit/src/test/scala/format/pgn/ReaderTest.scala

This include some changes on `pgn.Parser` to include the raw value of `San` in it's ADT, which is needed for us to return better error messages. This also matches `chessops` library's error messages.
here are two examples:
pgn:
```
1. e6
```
```diff
- Cannot play Pawn e6
+ Cannot play e6 at move 1 by White
```
pgn:
```
e3 Nc6 d4 Nf6 c3 e5 dxe5 Nxe5 Bb5 a6 Ba4 b5 Bb3 d5 e4 dxe4 f4 Qxd1+ Kxd1 Nd3 Be3 Ng4 Bd4 Ngf2+ Bxf2 Nxf2+ Ke1 Nxh1 Bd5 Ra7 Bc6+ Kd8 Bxe4 Bd6 g3 Re8 Nd2 f5 Ne2 fxe4 Kf1 e3 Kg2 exd2 Rxh1 Bb7+ Kf2 Bc5+ Kf3 d1=Q#
```
```diff
- Cannot play King f3
+ Cannot play Kf3 at move 25 by black
```

Improve error messages for `Reader.full` and friends

---

core/src/main/scala/format/pgn/Reader.scala
test-kit/src/test/scala/AntichessVariantTest.scala
test-kit/src/test/scala/Chess960Test.scala
test-kit/src/test/scala/DividerTest.scala
test-kit/src/test/scala/format/pgn/ReaderTest.scala

In `lila`, We only use `Complete/Incomplete` in `parseImport` https://github.com/lichess-org/lila/blob/dccd3486519f191818685d9b5d6c4b4125e86118/modules/tree/src/main/ParseImport.scala#L29-L32 which in turn doesn't care that much about `Complete/Incomplete` case either.
The changes need to make in `lila` is pretty minimal:
```diff
-          .pipe:
-            case Reader.Result.Complete(replay)          => (replay, none[ErrorStr])
-            case Reader.Result.Incomplete(replay, error) => (replay, error.some)
-          .pipe { (replay, relayError) =>
+          .pipe { case Reader.Result(replay, relayError) =>
```
This is my effort to reconcile two concepts: `Replay` and `Reader`. I believe they should become one.

Make `Reader.Result` a case class

---

core/src/main/scala/MoveOrDrop.scala
core/src/main/scala/Replay.scala
core/src/main/scala/Situation.scala
core/src/main/scala/format/pgn/parsingModel.scala
core/src/main/scala/variant/Atomic.scala
core/src/main/scala/variant/Variant.scala

Each variant needs to take care of it's own effect and do it when generating moves. This leads to simpler Variant trait, and also the whole code base as the other places don't need to know about effect anymore.

 Remove Variant.applyVariantEffect and friends

---

core/src/main/scala/Board.scala
core/src/main/scala/History.scala
core/src/main/scala/MoveOrDrop.scala
core/src/main/scala/Situation.scala
core/src/main/scala/bitboard/Board.scala
core/src/main/scala/format/BinaryFen.scala
core/src/main/scala/format/FenReader.scala
core/src/main/scala/variant/Crazyhouse.scala
core/src/main/scala/variant/ThreeCheck.scala
core/src/main/scala/variant/Variant.scala
test-kit/src/test/scala/CastlingKingSideTest.scala
test-kit/src/test/scala/CastlingQueenSideTest.scala
test-kit/src/test/scala/ChessTest.scala
test-kit/src/test/scala/PawnTest.scala
test-kit/src/test/scala/format/Visual.scala
test-kit/src/test/scala/perft/PerftTest.scala

Eventually we want to move history and variant to Situation, and use chess.bitboard.Board directly from Situation.

 Move CrazyData from Board to History

---

core/src/main/scala/History.scala
core/src/main/scala/MoveOrDrop.scala
core/src/main/scala/Position.scala
core/src/main/scala/variant/Antichess.scala
core/src/main/scala/variant/Atomic.scala
core/src/main/scala/variant/Chess960.scala
core/src/main/scala/variant/Crazyhouse.scala
core/src/main/scala/variant/FromPosition.scala
core/src/main/scala/variant/Horde.scala
core/src/main/scala/variant/KingOfTheHill.scala
core/src/main/scala/variant/RacingKings.scala
core/src/main/scala/variant/Standard.scala
core/src/main/scala/variant/ThreeCheck.scala
core/src/main/scala/variant/Variant.scala

- Removes `Variant.finalizeBoard` as We only use it in `CrazyHouse` and `ThreeCheck` to update the corresponding history. We apply this history update right after generate moves in `Variant.validMoves` instead.
- Move `generateMovesAt` logic to variant, this keeps variant's specific effect/state private and independent.

Remove variant.finalizeBoard

---

bench/src/main/scala/benchmarks/HashBench.scala
build.sbt
core/src/main/scala/Game.scala
core/src/main/scala/MoveOrDrop.scala
core/src/main/scala/Replay.scala
core/src/main/scala/format/pgn/Dumper.scala
core/src/main/scala/format/pgn/parsingModel.scala
core/src/main/scala/opening/OpeningDb.scala
core/src/main/scala/variant/Horde.scala
core/src/main/scala/variant/RacingKings.scala
test-kit/src/main/scala/chess/ChessTreeArbitraries.scala
test-kit/src/test/scala/HashTest.scala
test-kit/src/test/scala/perft/Perft.scala

`boardAfter` (which is a `Position` now), only has different color compare to finalizeAfter.
This also simplifies `finalizeAfter` implementation, make it leaner, less allocation and harder to have mistake.

Remove boardAfter and use finalizeAfter instead

---

core/src/main/scala/History.scala
core/src/main/scala/MoveOrDrop.scala
core/src/main/scala/format/pgn/parsingModel.scala
core/src/main/scala/variant/Crazyhouse.scala
core/src/main/scala/variant/Variant.scala
test-kit/src/test/scala/format/pgn/DumperTest.scala

Remove all of unneeded checks and calculation in `Variant.move`. We can just find move that have same destination and promotion as input. This also removes the need of `Move.withPromotion`.

Simplify Variant.move

---

core/src/main/scala/Position.scala

We did stop using these functions at some point. I checked `lila`, and there is only few places in tests that use one of these functions.

Remove unneeded Position.apply functions

---

core/src/main/scala/Node.scala

Did it in Github Edit, will wait for CI for correctness. I would also update `deleteAt`, but it requires `mapAccumulateFilter`, which I did implemented but not finished in in https://github.com/typelevel/cats/pull/4561

Use mapAccumulate

---

core/src/main/scala/Board.scala
core/src/main/scala/variant/Antichess.scala
core/src/main/scala/variant/Atomic.scala
core/src/main/scala/variant/Crazyhouse.scala
core/src/main/scala/variant/FromPosition.scala
core/src/main/scala/variant/KingOfTheHill.scala
core/src/main/scala/variant/Standard.scala
core/src/main/scala/variant/ThreeCheck.scala

We started to use `Standard` more when initialize other object
especially with `Standard.initialPosition`. This increases the chances
of deadlock when initializing classes. Locally it happen 50% of times I
run test. This commit is to reducing computation time when initialize
Standard, and also reducing reference of Standard from other variants.
- Use hard-coded initial Board for standard position
- Move initialPieces to def
- Derive initialPieces from initialBoard

fix deadlock class initialization

---

build.sbt

Just to use the new status code in [#17666](https://github.com/lichess-org/lila/pull/17666).

Bump scalachess version
