src/main/scala/Board.scala, src/main/scala/Replay.scala, src/main/scala/format/pgn/Reader.scala, src/main/scala/format/pgn/parsingModel.scala, src/main/scala/variant/Variant.scala
By importing import scalaz.Validation.FlatMap._
=> Removed ValidationFlatMapDeprecated scalaz compile warning

src/test/scala/DividerTest.scala
This particular test was failing after recent refactoring of `Divider`.
=> Fixed missing refactoring.

src/main/scala/OpeningDB.scala
http://lichess.org/forum/lichess-feedback/typo-opening-name#1
=> Fixes "Symmetrical Defence" spelling

src/main/scala/OpeningDB.scala
http://lichess.org/forum/lichess-feedback/a-minor-misspelling-franco-scilian
=> Fixes "Franco-Sicilian" spelling

src/main/scala/Board.scala, src/test/scala/HashTest.scala
Chasing an opening explorer bug ...
=> Add failing test for crazyhouse hash consistency

src/main/scala/Board.scala, src/test/scala/SituationTest.scala
=> playability with touching kings (ornicar/lila#1583)

src/test/scala/AtomicVariantTest.scala
the finally tested position, black to move:
=> fix test description: king is not in check

src/main/scala/History.scala, src/main/scala/format/Forsyth.scala, src/main/scala/variant/Crazyhouse.scala, src/test/scala/GameTest.scala, src/test/scala/HistoryTest.scala
Ok, this should be a reasonable way to fix it.
(Still the first position of a game does not count towards threefold repetition, but we knowingly accepted this before.)
=> Fix halfmove clock

.gitignore
these files are created with `sbt eclipse` in lila
=> ignore eclipse generated files

src/main/scala/Actor.scala, src/main/scala/Board.scala, src/main/scala/Castles.scala, src/main/scala/Drop.scala, src/main/scala/History.scala, src/main/scala/Move.scala, src/main/scala/Pos.scala, src/main/scala/Situation.scala, src/main/scala/format/Forsyth.scala, src/test/scala/PerftTest.scala, src/test/scala/format/ForsythTest.scala
https://en.wikipedia.org/wiki/X-FEN is a backwards compatible extension of normal FENs. FENs will only differ in situations where castling was broken previously.
Fixes #36 aka ornicar/lila#1849.
=> X-FEN support to fix ambiguous castling rights in a backwards compatible way

src/main/scala/Clock.scala
> maybe add a `remainingDuration(color: Color): FiniteDuration` function to scalachess' Clock?
yes, please :)
=> add Clock.remainingDuration for convenience

src/main/scala/Clock.scala
and don't remove time from clock on takeback
=> Add setRemainingCentis function

src/main/scala/Clock.scala, src/main/scala/Game.scala
For improving clock history and move time calc.
=> Don't add clock inc after game ends

src/main/scala/Clock.scala
`RunningClock.incrementOf` already exists. Make it available on the `Clock` trait for convenience.
=> add incrementOf(color) to clock trait

src/main/scala/Centis.scala, src/main/scala/Clock.scala, src/main/scala/Drop.scala, src/main/scala/Game.scala, src/main/scala/Move.scala, src/main/scala/Speed.scala, src/main/scala/Timestamp.scala, src/test/scala/BerserkTest.scala, src/test/scala/ClockTest.scala
Use fixed point math instead of floats.
=> Switch clock to centis precision

src/main/scala/Clock.scala
Centis rewrite swapped the logic for which time got decremented.
=> Fix Running->Paused clock transition.

src/main/scala/History.scala, src/main/scala/format/Forsyth.scala, src/test/scala/format/ForsythTest.scala
=> accept winboard-style threecheck fens

src/main/scala/Hash.scala, src/test/scala/HashTest.scala
=> Move hash test function into HashTest

src/main/scala/Centis.scala, src/main/scala/Clock.scala, src/main/scala/Color.scala, src/main/scala/DecayingStats.scala, src/main/scala/Drop.scala, src/main/scala/Game.scala, src/main/scala/LagTracker.scala, src/main/scala/Move.scala, src/main/scala/MoveMetrics.scala, src/test/scala/ClockTest.scala, src/test/scala/DecayingStatsTest.scala
- Add logic for receiving and storing client lag
- Track client lag using decaying average / decaying variance, for future piping to clients and ui enhancements
- Rewrite entire clock class and logic.
=> Clock rewrite for lag compensation improvements

src/main/scala/Centis.scala, src/main/scala/Clock.scala, src/test/scala/ClockTest.scala
Rewrite withGrace to ignore lag for non-active player.
=> Clean up Clock and add tests

src/main/scala/format/Forsyth.scala, src/main/scala/variant/Crazyhouse.scala, src/main/scala/variant/ThreeCheck.scala, src/test/scala/format/ForsythTest.scala
Reverts ornicar/scalachess#104
It breaks compatibility with the mobile app.
=> Revert "[RFC] switch to winboard fens"

src/main/scala/Clock.scala, src/main/scala/Game.scala
=> Hard stop clock on game ending moves

src/test/scala/ClockTest.scala
=> update expectations in clock test (fixes #133)

build.sbt, src/main/scala/Centis.scala, src/main/scala/Clock.scala, src/main/scala/Color.scala, src/main/scala/DecayingStats.scala, src/main/scala/LagTracker.scala, src/main/scala/Stats.scala, src/test/scala/StatsTest.scala
Collect additional stats for monitoring. Some stats (comp est)
are temporary and can be removed after estimates are considered
stable.
=> Collect addition lag statistics

src/main/scala/InsufficientMatingMaterial.scala, src/main/scala/variant/Horde.scala, src/main/scala/variant/Variant.scala, src/test/scala/HordeVariantTest.scala
This does not handle all corner cases, but should handle 99.99% of positions encountered in real horde games.
=> Update horde insufficient material and fortress detection

src/main/scala/StartingPosition.scala
Addressing: https://github.com/ornicar/lila/issues/4472
=> Add Sokolsky Opening to list of starting positions

src/main/scala/InsufficientMatingMaterial.scala, src/test/scala/VariantTest.scala
https://lichess.org/forum/lichess-feedback/isnt-this-a-draw-due-to-insufficient-mating-material#10
=> Apply insufficient material check when both players have bishops

src/main/scala/Actor.scala, src/test/scala/PerftTest.scala
=> h-side rook can block a-side castling (fixes ornicar/lila#4625)

src/main/scala/Actor.scala, src/test/scala/AtomicVariantTest.scala
=> Fix atomic castling with touching kings

src/main/scala/opening/FullOpeningPart2.scala
Zhuravlev Countergambit was announced in the Vienna game before black gambits anything.
=> Remove misclassified positions

src/main/scala/Board.scala, src/main/scala/Drop.scala, src/main/scala/History.scala, src/main/scala/Move.scala, src/main/scala/variant/Crazyhouse.scala, src/main/scala/variant/Variant.scala, src/test/scala/CrazyhouseVariantTest.scala, src/test/scala/format/ForsythTest.scala
See #109 for the goal this is trying to achieve.
Test failure seems unrelated and tests pass locally. Also tested the halfmove clock in a couple of games and on the analysis board.
/cc @isaacl
=> decouple halfmove clock from hashes (closes #109)

.travis.yml, README.md, project/plugins.sbt
The current coverage is pretty good, but there are a few classes that are not covered. I'll make another PR to test some of these classes.
=> Add scoverage

src/main/scala/StartingPosition.scala
This initial position was requested at the forums,
https://lichess.org/forum/lichess-feedback/tournament-creation-2
B01 Scandinavian Defense, Icelandic-Palme Gambit
1. e4 d5
2. exd5 Nf6
3. c4 e6
rnbqkb1r/ppp2ppp/4pn2/3P4/2P5/8/PP1P1PPP/RNBQKBNR w KQkq - 0 4
=> Add Scandinavian Defense, Icelandic-Palme Gambit

src/main/scala/StartingPosition.scala, src/main/scala/opening/FullOpeningPart2.scala
I mixed up a FEN position when creating PR #199 - resulting in the Rapport-Jobava system being placed mirrored. I double checked everything and fixed the error; apologies!
=> Fix Rapport-Jobava system

src/main/scala/format/pgn/Parser.scala, src/test/scala/format/pgn/ParserTest.scala, src/test/scala/format/pgn/RenderTest.scala
=> add test for issue 127

src/main/scala/InsufficientMatingMaterial.scala, src/main/scala/Piece.scala, src/main/scala/Pos.scala, src/main/scala/variant/Antichess.scala, src/main/scala/variant/Atomic.scala, src/main/scala/variant/Horde.scala
=> square color is not piece color

src/main/scala/Board.scala, src/main/scala/History.scala, src/main/scala/Pos.scala, src/main/scala/PosSet.scala, src/main/scala/format/Forsyth.scala, src/main/scala/variant/Atomic.scala, src/main/scala/variant/Crazyhouse.scala, src/main/scala/variant/KingOfTheHill.scala, src/test/scala/CrazyhouseVariantTest.scala, src/test/scala/format/ForsythTest.scala
Sets of `Pos` and now be naturally stored in a single `Long`.
=> introduce PosSet, a bitboard based Set[Pos]

src/main/scala/Actor.scala, src/test/scala/CastleTest.scala
See b04bb1a14c971b87ed4821daba738d5fd06c096e for a brief description of the issue.
=> fix chess960 castling dests in fromPosition

src/main/scala/format/pgn/model.scala, src/test/scala/format/pgn/RenderTest.scala
=> fix missing black move number after %clk

src/main/scala/format/pgn/Glyph.scala, src/main/scala/format/pgn/Parser.scala, src/main/scala/format/pgn/model.scala, src/test/scala/format/pgn/Fixtures.scala, src/test/scala/format/pgn/ParserTest.scala
Hey, this is my first attempt to this, and my first experience with `scala-parser-combinators`.  I’d welcome some feedback.
=> allow non-nag parsing #217

src/main/scala/format/FEN.scala
=> FEN: Add halfMove accessor

src/main/scala/format/pgn/Parser.scala
When importing PGNs at [lichess.org/paste](https://lichess.org/paste), including null moves results in a strange error message. It isn't very clear that the null move is the cause of the problem.
```
Cannot parse moves: [26.41] failure: end of input expected
win a Pawn by 20.Nxh6 (see below).} Nh7 (19... -- 20. Nxh6+ gxh6 21. Qxf6) 20.
^
```
This PR improves the error message and makes it point to the problematic move:
```
Cannot parse moves: [26.48] error: Lichess does not support null moves
win a Pawn by 20.Nxh6 (see below).} Nh7 (19... -- 20. Nxh6+ gxh6 21. Qxf6) 20.
^
```
The `guard` on line 117 isn't needed to make the code work, but it shifts the caret to point to the move instead of pointing to the space after the move.
Null move notation was chosen from what SCID and WinBoard …
=> Better error message for null moves in PGN parsing

src/main/scala/format/UciDump.scala
For ornicar/lila#9465
Not sure if there's a nicer way to do this 🤔
=> Allow forcing 960 UCI notation in UCIDump

src/main/scala/format/pgn/tagModel.scala
https://lichess.org/forum/lichess-feedback/importing-crazyhouse-pgn-from-cc
=> Convert chess.com 3-check PGN tag

project/build.properties
Update newest version of sbt.
I suggest that we use @scala-steward for taking care of project's dependencies.
=> Update sbt version 1.6.1

src/main/scala/format/pgn/Parser.scala
Some small things I noticed when I was trying to work on comment of Thibault in #239 .
=> Small improvement for error messages

src/main/scala/format/pgn/Parser.scala
Follow @johnynek suggestions in #239. The the performance is improved dramatically!
Here is a typical benchmark result in my machine:
```
55 games in 22 ms
55 games in 31 ms
55 games in 25 ms
55 games in 24 ms
55 games in 23 ms
55 games in 21 ms
55 games in 22 ms
55 games in 18 ms
55 games in 22 ms
55 games in 23 ms
Average = 420 microseconds per game
2380 games per second
```
Much faster compare to the previous implementation:
```
55 games in 49 ms
55 games in 45 ms
55 games in 47 ms
55 games in 81 ms
55 games in 44 ms
55 games in 41 ms
55 games in 46 ms
55 games in 41 ms
55 games in 83 ms
55 games in 46 ms
Average = 950 microseconds per game
1052 games per second
```
And old `scala-parser-combinators` implementation:
```
55 games in 127 ms
55 games in 101 ms
55 games in 89 ms
55 games …
```
=> Improve pgn parser performance

src/main/scala/format/pgn/Parser.scala, src/test/scala/format/pgn/Fixtures.scala, src/test/scala/format/pgn/ParserTest.scala
This fixed issue https://github.com/ornicar/lila/issues/10360.
=> Ignore comments/invalid moves at the end of pgn file

src/main/scala/format/pgn/tagModel.scala, src/test/scala/format/pgn/RenderTest.scala
potential fix for: https://github.com/lichess-org/lila/issues/10554
=> Fix tag with doublequote

.scalafmt.conf, src/main/scala/format/pgn/Parser.scala, src/main/scala/format/pgn/model.scala, src/main/scala/format/pgn/parsingModel.scala, src/test/scala/BoardReplayPerfTest.scala, src/test/scala/CastleTest.scala, src/test/scala/DividerPerfTest.scala, src/test/scala/format/UciDumpPerfTest.scala
* Set running dialect to scala213
* Change config to make scalafmt ignore comments
* Reformat all files
=> Bump scalafmt core 3.5.0

src/main/scala/format/pgn/Parser.scala, src/test/scala/format/pgn/Fixtures.scala, src/test/scala/format/pgn/ParserTest.scala
This also removes the last piece of preprocess string.
=> Support pgn escape mechanism %

src/main/scala/Drop.scala, src/main/scala/Move.scala, src/test/scala/CrazyhouseVariantTest.scala
=> hash finalized crazyhouse board after capture

.github/workflows/ci.yml
=> Regenerate github workflow

src/main/scala/variant/Antichess.scala, src/main/scala/variant/Atomic.scala, src/main/scala/variant/Chess960.scala, src/main/scala/variant/Crazyhouse.scala, src/main/scala/variant/FromPosition.scala, src/main/scala/variant/Horde.scala, src/main/scala/variant/KingOfTheHill.scala, src/main/scala/variant/RacingKings.scala, src/main/scala/variant/Standard.scala, src/main/scala/variant/ThreeCheck.scala, src/main/scala/variant/Variant.scala
useful for at least https://github.com/lichess-org/lila/blob/07818072be9f6a66f8f5055f7c6c251ce421ced0/modules/analyse/src/main/ExternalEngine.scala#L74
=> add UCI_Variant name of each variant

README.md, bench/src/main/scala/benchmarks/ParserBench.scala, bench/src/main/scala/benchmarks/PerftBench.scala, bench/src/main/scala/benchmarks/PlayBench.scala
Also apply some best practices here: https://www.baeldung.com/java-microbenchmark-harness
=> Update jmh configration paramenters to reduce run time

src/main/scala/Situation.scala, src/main/scala/bitboard/Board.scala, src/main/scala/bitboard/OpaqueBitboard.scala
Also replace one cryptic used of `unfold` by `fold`
=> Clean up Bitboard api

src/main/scala/Situation.scala, src/main/scala/bitboard/OpaqueBitboard.scala, src/main/scala/format/pgn/model.scala
=> Simplify Situation.genEnpassant

src/main/scala/Board.scala, src/main/scala/format/FenReader.scala, src/test/scala/AntichessVariantTest.scala
- Ignore castling when for Antichess when reading Fen
- Set `unmovedRooks` to none when init Antichess Board
=> Antichess castling

src/main/scala/format/pgn/Parser.scala, src/test/scala/format/pgn/ParserTest.scala
Fix https://github.com/lichess-org/lichobile/issues/2283
=> Support nbsp in pgn parser

src/main/scala/bitboard/Bitboard.scala, src/main/scala/variant/Crazyhouse.scala, src/test/scala/perft/FullPerftTest.scala, src/test/scala/perft/Perft.scala, src/test/scala/perft/PerftTest.scala
Implement all possible drops for crazyhouse and use it for perft tests.
=> Crazyhouse perft

src/main/scala/format/pgn/Parser.scala, src/test/scala/format/pgn/ErrorMessagesTest.scala
It's the only error where Lichess is mentioned
=> Remove Lichess from the null move error message

src/main/scala/Situation.scala, src/main/scala/bitboard/Board.scala, src/main/scala/variant/Standard.scala, src/test/scala/bitboard/BoardTest.scala
Nothing change much: https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/2b85647cfaa7f3ae43f2ad3f4b15e40c/raw/6f2568a167e05ee7ae862838a8acd7715a7b36cc/14.7.1,https://gist.githubusercontent.com/lenguyenthanh/2b85647cfaa7f3ae43f2ad3f4b15e40c/raw/6f2568a167e05ee7ae862838a8acd7715a7b36cc/pr.json
=> Small optimization for sliderBlockers

src/main/scala/variant/Variant.scala, src/test/scala/HordeVariantTest.scala
This is supposed a failed test but it passed
=> Add test for https://lichess.org/2TMwa66b#115

src/main/scala/format/UciCharPair.scala, src/main/scala/format/UciPath.scala, src/test/scala/Arbitraries.scala, src/test/scala/format/UciChairPairTest.scala, src/test/scala/format/UciPathTest.scala
Add `UciChairPair.toUci` and `UciPath.debug` functions
They can be useful for debugging, especially when working with study.
=> Add toUci function for UciCharPair

src/main/scala/Node.scala, src/test/scala/Arbitraries.scala, src/test/scala/NodeTest.scala
=> More node functions prepare for lila-chess-tree

src/main/scala/format/pgn/Parser.scala, src/test/scala/format/pgn/Fixtures.scala, src/test/scala/format/pgn/ParserTest.scala
Fix https://github.com/lichess-org/lila/issues/9636
=> Support ep postfix in enpassant in pgn parser

bench/src/main/scala/benchmarks/HashBench.scala, bench/src/main/scala/benchmarks/InsufficientMaterialBench.scala, bench/src/main/scala/benchmarks/ParserBench.scala, bench/src/main/scala/benchmarks/PerftBench.scala, bench/src/main/scala/benchmarks/PlayBench.scala
- Reduce number of games and nodes for PerftBench
- Change val => var
- Move unrelated calculation out from benchmarks
- Use more of Blackhole to consume results/ burn cpu to simulate real world scenarios 
- @Fork = 3
- Fix HashBench
=> Improve benchmarks

src/main/scala/File.scala, src/main/scala/Hash.scala, src/main/scala/Rank.scala, src/main/scala/Situation.scala, src/main/scala/Square.scala, src/main/scala/bitboard/Bitboard.scala, src/main/scala/format/FenWriter.scala, src/main/scala/format/UciCharPair.scala, src/main/scala/format/pgn/Parser.scala, src/main/scala/format/pgn/parsingModel.scala, src/main/scala/variant/Horde.scala, src/test/scala/NodeLawsTest.scala, src/test/scala/bitboard/BoardTest.scala, src/test/scala/format/UciChairPairTest.scala, src/test/scala/format/pgn/ParserTest.scala
Not as much as I expected but I take it.
[link](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/1b37119a06b58ea06dcebc8b23152314/raw/69790e39536e0fd87ec05ac21c9ca5cfd1683dcd/15.5.0.json,https://gist.githubusercontent.com/lenguyenthanh/3537b514f9fe390e46da8ae0412d8e28/raw/35f91e5dc4b8527d14ab6c728de915680d01fa45/Square.json)
=> Square, File, Rank without newtypes

bench/src/main/scala/benchmarks/DestinationsBench.scala, src/main/scala/Situation.scala, src/test/scala/AntichessVariantTest.scala, src/test/scala/ChessTest.scala, src/test/scala/CrazyhouseVariantTest.scala
benchmark result
```
[info] Benchmark                           Mode  Cnt       Score      Error  Units
[info] DestinationsBench.bitboard         thrpt   45  176810.178 ±  635.485  ops/s
[info] DestinationsBench.current          thrpt   45  113807.811 ± 1726.145  ops/s
```
Benchmark code: https://gist.github.com/lenguyenthanh/9830485f1577dadcd3d30eba7d329ee7
P/s: I'll see if I can improve FenWriter, then I'll cut a release.
=> Optimize Situation.destinations with bitboard

bench/src/main/scala/benchmarks/FenReaderBench.scala, bench/src/main/scala/benchmarks/FenWriterBench.scala, src/main/scala/Board.scala, src/main/scala/Piece.scala, src/main/scala/bitboard/Bitboard.scala, src/main/scala/bitboard/Board.scala, src/main/scala/format/Fen.scala, src/main/scala/format/FenReader.scala, src/main/scala/format/FenWriter.scala, src/main/scala/variant/Crazyhouse.scala, src/test/scala/ChessTest.scala, src/test/scala/VariantTest.scala, src/test/scala/format/Visual.scala
Benchmarks:
or [link](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/lenguyenthanh/e842140c51c41bbd084acd723c82ace4/raw/f5a395d25f2b24edd12f9ee6d2a2007f39a7d779/original.json,https://gist.githubusercontent.com/lenguyenthanh/e842140c51c41bbd084acd723c82ace4/raw/95468ca20402548f41b8c99ee1b1b6cff899f8ab/final.json)
=> Improve Fen Reader/Writer performance

src/main/scala/variant/RacingKings.scala, src/test/scala/VariantTest.scala
Racing kings should have no check at all so it is easy to identify impossible checks.
=> Add impossible check validation for racing kings variant.

src/main/scala/format/pgn/tagModel.scala, test-kit/src/test/scala/format/pgn/Fixtures.scala, test-kit/src/test/scala/format/pgn/ParserTest.scala, test-kit/src/test/scala/format/pgn/TagTest.scala
for https://github.com/lichess-org/lila/issues/13695
=> Trim PGN Tag content

src/main/scala/bitboard/Bitboard.scala, src/main/scala/format/FenReader.scala, test-kit/src/test/scala/bitboard/BitboardTest.scala, test-kit/src/test/scala/format/FenTest.scala
=> Fix Fen Reader regression

src/main/scala/Castles.scala, src/main/scala/History.scala, src/main/scala/bitboard/Bitboard.scala, src/main/scala/format/FenWriter.scala, src/main/scala/variant/Horde.scala, test-kit/src/test/scala/CastlesTest.scala, test-kit/src/test/scala/HordeVariantTest.scala, test-kit/src/test/scala/VariantTest.scala, test-kit/src/test/scala/format/FenTest.scala
=> Fix x fen notation when writing

bench/src/main/scala/benchmarks/BinaryFenBench.scala, core/src/main/scala/format/BinaryFen.scala, test-kit/src/test/scala/format/BinaryFenTest.scala
https://discord.com/channels/280713822073913354/352976626558042122/1226546841076891769
=> `case class BinaryFen(value: Array[Byte])` implementing `equals`

core/src/main/scala/HasId.scala, test-kit/src/test/scala/HasIdTest.scala
I failed to run tests and scared to run benchmarks, so I will rely on CI. I hope this code works the same as previous one, and improves performance.
=> Simplify removeById

core/src/main/scala/format/pgn/model.scala
New anonymous class definition will be duplicated at each inline site
=> Remove inline as it causes warning as below

build.sbt
=> Add bench to list of aggregate projects

core/src/main/scala/Node.scala, test-kit/src/test/scala/NodeTest.scala
And implement a more sensible Node.take function
This is a breaking change to lila
Prepare for another improvement for pgn render
=>  Add getMainlineNodeAt and modifyInMainlineAt 

core/src/main/scala/File.scala, core/src/main/scala/Rank.scala, test-kit/src/main/scala/chess/CoreArbitraries.scala
Add some needed arbitraries for https://github.com/lichess-org/lila/pull/16150
=> Improve core arbitrary

core/src/main/scala/Divider.scala
=> Use collectFirst instead of manual foldLeft

bench/src/main/scala/benchmarks/BinaryFenBench.scala
Increase number of test cases and try to remove changes of compiler
trying to constant folding
=> Improve BinaryFen benchmark

core/src/main/scala/Replay.scala, core/src/main/scala/Situation.scala, core/src/main/scala/format/pgn/Binary.scala, core/src/main/scala/format/pgn/Glyph.scala, core/src/main/scala/format/pgn/Parser.scala, core/src/main/scala/format/pgn/Pgn.scala, core/src/main/scala/model.scala
Also privatize some private functions
=> More type annotation for public functions

core/src/main/scala/Replay.scala, core/src/main/scala/format/pgn/Reader.scala, test-kit/src/test/scala/ReplayTest.scala, test-kit/src/test/scala/format/pgn/ReaderTest.scala
=> Improve error message for Replay.gameMoveWhileValid

core/src/main/scala/format/FenWriter.scala
They're the common denominator of all Fen.write
=> Add Fen.write(Situation, FullMoveNumber)

bench/src/main/scala/benchmarks/PlayBench.scala, build.sbt, core/src/main/scala/Game.scala, core/src/main/scala/Position.scala, core/src/main/scala/Replay.scala, core/src/main/scala/format/BinaryFen.scala, core/src/main/scala/format/FenWriter.scala, core/src/main/scala/format/pgn/Reader.scala, core/src/main/scala/format/pgn/parsingModel.scala, test-kit/src/test/scala/AntichessVariantTest.scala, test-kit/src/test/scala/AtomicVariantTest.scala, test-kit/src/test/scala/AutodrawTest.scala, test-kit/src/test/scala/CastlingKingSideTest.scala, test-kit/src/test/scala/CastlingQueenSideTest.scala, test-kit/src/test/scala/Chess960Test.scala, test-kit/src/test/scala/ChessTest.scala, test-kit/src/test/scala/CrazyhouseVariantTest.scala, test-kit/src/test/scala/GameTest.scala, test-kit/src/test/scala/HashTest.scala, test-kit/src/test/scala/HordeVariantTest.scala, test-kit/src/test/scala/InsufficientMatingMaterialTest.scala, test-kit/src/test/scala/PlayTest.scala, test-kit/src/test/scala/RacingKingsVariantTest.scala, test-kit/src/test/scala/UnmovedRooksTest.scala, test-kit/src/test/scala/VariantTest.scala, test-kit/src/test/scala/format/pgn/DumperTest.scala, test-kit/src/test/scala/format/pgn/ReaderTest.scala
- rename Game.{board => position}
- rename AndFullMoveNumber{board => position}
=> Rename board to position

core/src/main/scala/Bitboard.scala, core/src/main/scala/Board.scala, core/src/main/scala/File.scala, core/src/main/scala/Piece.scala, core/src/main/scala/Rank.scala, core/src/main/scala/format/BinaryFen.scala, core/src/main/scala/format/FenReader.scala, test-kit/src/test/scala/bitboard/BitboardTest.scala, test-kit/src/test/scala/bitboard/BoardTest.scala
- Add type annotations and cleanup for Role
- Remove one extra allocation for FenReader
- Remove unused that much Board.apply
=> Improve Board.pieceAt and other

core/src/main/scala/format/pgn/parsingModel.scala, core/src/main/scala/variant/Variant.scala, test-kit/src/test/scala/VariantTest.scala, test-kit/src/test/scala/format/pgn/DumperTest.scala
https://lichess.org/forum/lichess-feedback/pawn-promotion-does-not-work
=> Fix lichobile backward compatibility

core/src/main/scala/Replay.scala
I did it in Github edit, will wait for pipelines
=> Revise computeReplay

core/src/main/scala/Bitboard.scala, core/src/main/scala/Board.scala, core/src/main/scala/InsufficientMatingMaterial.scala, core/src/main/scala/variant/Variant.scala, test-kit/src/test/scala/HordeInsufficientMaterialTest.scala, test-kit/src/test/scala/InsufficientMatingMaterialTest.scala, test-kit/src/test/scala/bitboard/BitboardTest.scala
- Add comments and refactor code to make the intentions clearer
- Add some utility functions & comments for Board and Bitboard
=> Improvement for `InsufficientMatingMaterial.apply`

bench/src/main/scala/benchmarks/PlayBench.scala, core/src/main/scala/CanPlay.scala, core/src/main/scala/Position.scala, core/src/main/scala/Replay.scala, test-kit/src/test/scala/AtomicVariantTest.scala, test-kit/src/test/scala/CanPlayTest.scala, test-kit/src/test/scala/HordeVariantTest.scala, test-kit/src/test/scala/ReplayTest.scala
- **Add Canplay.buildTree**
- **Remove Replay.gameMoveWhileValid**
- **Use ply from initial game state**
- **Implement Canplay.foreach**
=> Canplay improvements

core/src/main/scala/format/pgn/Tag.scala
see https://gist.github.com/SergioGlorias/90c59fde2a345334be19888ed28f86c6#file-game-idchess-pgn
=> idchess.com also use time online
